safe: true
markdown: rdiscount
highlighter: pygments
permalink: pretty

exclude:
    - Makefile
    - README.md
    - bower.json
    - static/style/style.less
    - static/vendor

paginate: 7

sass:
  style: compressed
