safe: true
markdown: kramdown
highlighter: rouge
permalink: pretty

exclude:
    - _env/
    - Makefile
    - README.md
    - bower.json
    - static/style/style.less
    - static/vendor

paginate: 7

sass:
  style: compressed
